<?php
// If the all the variables are set when the Submit button is clicked...
if (isset($_POST['field_submit'])) {
    // Refer to conn.php file and open a connection.
    require_once("conn.php");
    // Will get the value typed in the form text field and save into variable
    $var_director = $_POST['offense_input'];
    $query = "CALL getOffense(:offense)";

try
    {
      // Create a prepared statement. Prepared statements are a way to eliminate SQL INJECTION.
      $prepared_stmt = $dbo->prepare($query);
      //bind the value saved in the variable $var_director to the place holder :ph_director  
      // Use PDO::PARAM_STR to sanitize user string.
      $prepared_stmt->bindValue(':offense', $var_director, PDO::PARAM_STR);
      $prepared_stmt->execute();
      // Fetch all the values based on query and save that to variable $result
      $result = $prepared_stmt->fetchAll();

    }
    catch (PDOException $ex)
    { // Error in database processing.
      echo $sql . "<br>" . $error->getMessage(); // HTTP 500 - Internal Server Error
    }
}
?>

<html>
<!-- Any thing inside the HEAD tags are not visible on page.-->
  <head>
    <!-- THe following is the stylesheet file. The CSS file decides look and feel -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
     <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <script>
  $( function() {
    var availableTags  = ["A.B.C.,FALSE PROOF OF AGE","ABANDON ANIMAL","ABORTION 1","ABORTION 2, 1, SELF","ABORTIONAL ARTICLES,ISSUING","ABSCONDING FROM WORK RELEASE 2","ACCOSTING,FRAUDULENT","ADM.CODE,UNCLASSIFIED MISDEMEA","ADM.CODE,UNCLASSIFIED VIOLATIO","AGGRAVATED CRIMINAL CONTEMPT","AGGRAVATED HARASSMENT 1","AGGRAVATED HARASSMENT 2","AGGRAVATED SEXUAL ASBUSE","AGRICULTURE & MARKETS LAW,UNCL","AIR POLLUTION-MOTOR VEH (ADM C","AIRPOLLUTION","ALCOHOLIC BEVERAGE CONTROL LAW","ALCOHOLIC BEVERAGES,PUBLIC CON","ANARCHY,CRIMINAL","APPEARANCE TICKET FAIL TO RESP","ARSON 1","ARSON 2,3,4","ARSON, MOTOR VEHICLE 1 2 3 & 4","ASSAULT 2,1,UNCLASSIFIED","ASSAULT 3","ASSAULT OTHER PUBLIC SERVICE EMPLOYEE","ASSAULT POLICE/PEACE OFFICER","ASSAULT SCHOOL SAFETY AGENT","ASSAULT TRAFFIC AGENT","ASSEMBLY,UNLAWFUL","ATTEND/SPECTATOR ANIMAL FIGHTING","BAIL JUMPING 1 & 2","BAIL JUMPING 3","BIGAMY","BREED/TRAIN/HOST ANIMAL FIGHTING","BRIBERY, POLICE OFFICER","BRIBERY,COMMERCIAL","BRIBERY,FRAUD","BRIBERY,PUBLIC ADMINISTRATION","BUILDING MATERIAL","BURGLARS TOOLS,UNCLASSIFIED","BURGLARY, TRUCK UNKNOWN TIME","BURGLARY,COMMERCIAL,DAY","BURGLARY,COMMERCIAL,NIGHT","BURGLARY,COMMERCIAL,UNKNOWN TI","BURGLARY,RESIDENCE,DAY","BURGLARY,RESIDENCE,NIGHT","BURGLARY,RESIDENCE,UNKNOWN TIM","BURGLARY,TRUCK DAY","BURGLARY,TRUCK NIGHT","BURGLARY,UNCLASSIFIED,DAY","BURGLARY,UNCLASSIFIED,NIGHT","BURGLARY,UNCLASSIFIED,UNKNOWN","BURGLARY,UNKNOWN TIME","CAUSE SPI/KILL ANIMAL","CHECK,BAD","CHILD ABANDONMENT","CHILD, ENDANGERING WELFARE","CHILD,ALCOHOL SALE TO","CHILD,LICENSED PREMISES","CHILD,OFFENSES AGAINST,UNCLASS","CIGARETTE,NO TAX STAMP,POSSESS","COERCION 1","COERCION 2","COMPUTER TAMPER/TRESSPASS","COMPUTER UNAUTH. USE/TAMPER","CONFINING ANIMAL IN VEHICLE/SHELTER","CONSPIRACY 2, 1","CONSPIRACY 4, 3","CONSPIRACY 6, 5","CONTEMPT,CRIMINAL","CONTROLLED SUBSTANCE, INTENT T","CONTROLLED SUBSTANCE, POSSESSI","CONTROLLED SUBSTANCE, SALE 4","CONTROLLED SUBSTANCE, SALE 5","CONTROLLED SUBSTANCE,INTENT TO","CONTROLLED SUBSTANCE,POSSESS.","CONTROLLED SUBSTANCE,POSSESS.-","CONTROLLED SUBSTANCE,SALE 1","CONTROLLED SUBSTANCE,SALE 2","CONTROLLED SUBSTANCE,SALE 3","COURSE OF SEXUAL CONDUCT AGAIN","CREDIT CARD,UNLAWFUL USE OF","CRIMINAL CONTEMPT 1","CRIMINAL DISPOSAL FIREARM 1 &","CRIMINAL MIS 2 & 3","CRIMINAL MISCHIEF 4TH, GRAFFIT","CRIMINAL MISCHIEF,UNCLASSIFIED 4","CUSTODIAL INTERFERENCE 1","CUSTODIAL INTERFERENCE 2","DIS. CON.,AGGRAVATED","DISORDERLY CONDUCT","DISSEMINATING A FALSE SEX OFFEND","DOG STEALING","DRUG PARAPHERNALIA,   POSSESSE","DRUG, INJECTION OF","EAVESDROPPING","EDUCATION LAW","EDUCATION LAW, TRUANCY","EDUCATION LAW,STREET TRADE","EDUCATION LAW,UNCLASSIFIED","END WELFARE VULNERABLE ELDERLY PERSON","ENTERPRISE CORRUPTION","ENVIRONMENTAL CONTROL BOARD","ESCAPE 2,1","ESCAPE 3","EXPOSURE OF A PERSON","FAC. SEXUAL OFFENSE W/CONTROLL","FACILITATION 3,2,1, CRIMINAL","FACILITATION 4, CRIMINAL","FALSE ALARM FIRE","FALSE REPORT 1,FIRE","FALSE REPORT BOMB","FALSE REPORT UNCLASSIFIED","FIREARMS LICENSING LAWS","FIREWORKS","FIREWORKS PREV CONV 5 YEARS","FIREWORKS, POSSESS/USE","FIREWORKS, SALE","FORGERY-ILLEGAL POSSESSION,VEH","FORGERY,DRIVERS LICENSE","FORGERY,ETC.-MISD.","FORGERY,ETC.,UNCLASSIFIED-FELO","FORGERY,M.V. REGISTRATION","FORGERY,PRESCRIPTION","FORTUNE TELLING","FRAUD,UNCLASSIFIED-FELONY","FRAUD,UNCLASSIFIED-MISDEMEANOR","GAMBLING 1,PROMOTING,BOOKMAKIN","GAMBLING 1,PROMOTING,POLICY","GAMBLING 2, PROMOTING, BOOKMAK","GAMBLING 2, PROMOTING, POLICY-","GAMBLING 2,PROMOTING,UNCLASSIF","GAMBLING, DEVICE, POSSESSION","GENERAL BUSINESS LAW / UNCLASSIFIED","GENERAL BUSINESS LAW,TICKET SP","GRAFFITI (ADMINISTRATIVE CODE-","GRAND LARCENY-CHECK FROM MAILB","GYPSY CAB","HARASSMENT,SUBD 1,CIVILIAN","HARASSMENT,SUBD 3,4,5","HEALTH CODE,UNCLASSIFIED MISDE","HEALTH CODE,VIOLATION","HEALTHCARE/RENT.REG.","HIND PROSEC. TERR 2","HOMICIDE, NEGLIGENT, VEHICLE,","HOMICIDE,NEGLIGENT,UNCLASSIFIE","HOMICIDE,NEGLIGENT,VEHICLE","IMITATION PISTOL/AIR RIFLE","IMPAIRED DRIVING,DRUG","IMPERSONATION 1, POLICE OFFICE","IMPERSONATION 2, PUBLIC SERVAN","IMPRISONMENT 1,UNLAWFUL","IMPRISONMENT 2,UNLAWFUL","INAPPROPIATE SHELTER DOG LEFT","INCEST","INCOMPETENT PERSON,KNOWINGLY ENDANGERING","INCOMPETENT PERSON,RECKLESSY ENDANGERING","INTOXICATED DRIVING,ALCOHOL","JOSTLING","KIDNAPPING 1","KIDNAPPING 2","LABOR LAW,EMPLOYING CHILDREN","LABOR TRAFFICKING","LARCENY, GRAND OF AUTO - ATTEM","LARCENY, GRAND OF MOPED","LARCENY, PETIT OF AUTO - ATTEM","LARCENY, PETIT OF MOPED","LARCENY,GRAND BY ACQUIRING LOS","LARCENY,GRAND BY ACQUIRING LOST CREDIT CARD","LARCENY,GRAND BY BANK ACCT COMPROMISE-ATM TRANSACTION","LARCENY,GRAND BY BANK ACCT COMPROMISE-REPRODUCED CHECK","LARCENY,GRAND BY BANK ACCT COMPROMISE-TELLER","LARCENY,GRAND BY BANK ACCT COMPROMISE-UNAUTHORIZED PURCHASE","LARCENY,GRAND BY BANK ACCT COMPROMISE-UNCLASSIFIED","LARCENY,GRAND BY CREDIT CARD ACCT COMPROMISE-EXISTING ACCT","LARCENY,GRAND BY CREDIT CARD COMPROMISE-UNAUTHORIZE PURCHASE","LARCENY,GRAND BY DISHONEST EMP","LARCENY,GRAND BY EXTORTION","LARCENY,GRAND BY FALSE PROMISE","LARCENY,GRAND BY FALSE PROMISE-IN PERSON CONTACT","LARCENY,GRAND BY FALSE PROMISE-NOT IN PERSON CONTACT","LARCENY,GRAND BY IDENTITY THEFT-UNCLASSIFIED","LARCENY,GRAND BY OPEN BANK ACCT","LARCENY,GRAND BY OPEN CREDIT CARD (NEW ACCT)","LARCENY,GRAND BY OPEN/COMPROMISE CELL PHONE ACCT","LARCENY,GRAND BY THEFT OF CREDIT CARD","LARCENY,GRAND FROM BOAT, UNATTENDED","LARCENY,GRAND FROM BUILDING (NON-RESIDENCE) UNATTENDED","LARCENY,GRAND FROM COIN MACHIN","LARCENY,GRAND FROM EATERY, UNATTENDED","LARCENY,GRAND FROM NIGHT CLUB, UNATTENDED","LARCENY,GRAND FROM OPEN AREAS, UNATTENDED","LARCENY,GRAND FROM PARKING MET","LARCENY,GRAND FROM PERSON, BAG OPEN/DIP","LARCENY,GRAND FROM PERSON,LUSH WORKER(SLEEPING/UNCON VICTIM)","LARCENY,GRAND FROM PERSON,PERSONAL ELECTRONIC DEVICE(SNATCH)","LARCENY,GRAND FROM PERSON,PICK","LARCENY,GRAND FROM PERSON,PURS","LARCENY,GRAND FROM PERSON,UNCL","LARCENY,GRAND FROM PIER, UNATTENDED","LARCENY,GRAND FROM RESIDENCE, UNATTENDED","LARCENY,GRAND FROM RESIDENCE/BUILDING,UNATTENDED, PACKAGE THEFT INSIDE","LARCENY,GRAND FROM RESIDENCE/BUILDING,UNATTENDED, PACKAGE THEFT OUTSIDE","LARCENY,GRAND FROM RETAIL STORE, UNATTENDED","LARCENY,GRAND FROM STORE-SHOPL","LARCENY,GRAND FROM TRUCK, UNATTENDED","LARCENY,GRAND FROM VEHICLE/MOTORCYCLE","LARCENY,GRAND OF AUTO","LARCENY,GRAND OF BICYCLE","LARCENY,GRAND OF BOAT","LARCENY,GRAND OF MOTORCYCLE","LARCENY,GRAND OF TRUCK","LARCENY,GRAND OF VEHICULAR/MOTORCYCLE ACCESSORIES","LARCENY,GRAND PERSON,NECK CHAI","LARCENY,PETIT BY ACQUIRING LOS","LARCENY,PETIT BY CHECK USE","LARCENY,PETIT BY CREDIT CARD U","LARCENY,PETIT BY DISHONEST EMP","LARCENY,PETIT BY FALSE PROMISE","LARCENY,PETIT FROM AUTO","LARCENY,PETIT FROM BOAT","LARCENY,PETIT FROM BUILDING,UN","LARCENY,PETIT FROM BUILDING,UNATTENDED, PACKAGE THEFT INSIDE","LARCENY,PETIT FROM BUILDING,UNATTENDED, PACKAGE THEFT OUTSIDE","LARCENY,PETIT FROM COIN MACHIN","LARCENY,PETIT FROM OPEN AREAS,","LARCENY,PETIT FROM PARKING MET","LARCENY,PETIT FROM PIER","LARCENY,PETIT FROM STORE-SHOPL","LARCENY,PETIT FROM TRUCK","LARCENY,PETIT OF AUTO","LARCENY,PETIT OF BICYCLE","LARCENY,PETIT OF BOAT","LARCENY,PETIT OF LICENSE PLATE","LARCENY,PETIT OF MOTORCYCLE","LARCENY,PETIT OF TRUCK","LARCENY,PETIT OF VEHICLE ACCES","LEAVING SCENE-ACCIDENT-PERSONA","LEWDNESS,PUBLIC","LOITERING 1ST DEGREE FOR DRUG","LOITERING FOR PROSTITUTION OR","LOITERING TO PROMOTE PROSTITUT","LOITERING,DEVIATE SEX","LOITERING,GAMBLING,OTHER","LOITERING,SCHOOL","LOITERING,UNCLASSIFIED","LURING A CHILD","MAKING TERRORISTIC THREAT","MANUFACTURE UNAUTHORIZED RECOR","MARIJUANA, POSSESSION","MARIJUANA, POSSESSION 1, 2 & 3","MARIJUANA, POSSESSION 4 & 5","MARIJUANA, SALE 1, 2 & 3","MARIJUANA, SALE 4 & 5","MARRIAGE,OFFENSES AGAINST,UNCL","MATERIAL              OFFENSIV","MENACING 1ST DEGREE (VICT NOT","MENACING 1ST DEGREE (VICT PEAC","MENACING,PEACE OFFICER","MENACING,UNCLASSIFIED","MISCHIEF 1,CRIMINAL,EXPLOSIVE","MISCHIEF, CRIMINAL 3 & 2, OF M","MISCHIEF, CRIMINAL 3&2, BY FIR","MISCHIEF, CRIMINAL 4, BY FIRE","MISCHIEF, CRIMINAL 4, OF MOTOR","MISCHIEF,CRIMINAL,    UNCL 2ND","MONEY LAUNDERING 1 & 2","N.Y.C. TRANSIT AUTH. R&R","NAVIGATION LAW","NEGLECT/POISON ANIMAL","NOISE,UNECESSARY","NUISANCE, CRIMINAL","NUISANCE,CRIMINAL,UNCLASSIFIED","NY STATE LAWS,UNCLASSIFIED FEL","NY STATE LAWS,UNCLASSIFIED MIS","NY STATE LAWS,UNCLASSIFIED VIO","OBSCENE MATERIAL - UNDER 17 YE","OBSCENITY 1","OBSCENITY, MATERIAL 3","OBSCENITY, PERFORMANCE 3","OBSTR BREATH/CIRCUL","PARK R&R,GAMBLING","PARKR&R,UNCLASSIFIED VIOLATION","PEDDLING,UNLAWFUL","PERJURY 2,1,ETC","PERJURY 3,ETC.","PETIT LARCENY OF ANIMAL","PETIT LARCENY-CHECK FROM MAILB","PLACE FALSE BOMB","POSS METH MANUFACT MATERIAL","POSSES OR CARRY A KNIFE","POSSESS PARAPHERNALIA/ANIMAL FIGHTING","POSSESSION ANTI-SECURITY ITEM","POSSESSION HYPODERMIC INSTRUME","POSTING ADVERTISEMENTS","PRIVACY,OFFENSES AGAINST,UNCLA","PROMOTING A SEXUAL PERFORMANCE","PROMOTING SUICIDE ATTEMPT","PROSTITUTION","PROSTITUTION 1, UNDER 11","PROSTITUTION 2, COMPULSORY","PROSTITUTION 2, UNDER 16","PROSTITUTION 3, PROMOTING UNDE","PROSTITUTION 3,PROMOTING BUSIN","PROSTITUTION 4,PROMOTING&SECUR","PROSTITUTION, PATRONIZING 2, 1","PROSTITUTION, PATRONIZING 4, 3","PROSTITUTION,PERMITTING","PUBLIC ADMINISTATION,UNCLASS M","PUBLIC ADMINISTRATION,UNCLASSI","PUBLIC HEALTH LAW,GLUE,INHALAT","PUBLIC HEALTH LAW,GLUE,UNLAWFU","PUBLIC HEALTH LAW,UNCLASSIFIED","PUBLIC SAFETY,UNCLASSIFIED MIS","RADIO DEVICES,UNLAWFUL POSSESS","RAPE 1","RAPE 1,ATTEMPT","RAPE 2","RAPE 3","RECKLESS DRIVING","RECKLESS ENDANGERMENT 1","RECKLESS ENDANGERMENT 2","RECKLESS ENDANGERMENT OF PROPE","RECORDS,FALSIFY-TAMPER","RESISTING ARREST","RIOT 1","RIOT 2/INCITING","ROBBERY, CHAIN STORE","ROBBERY, PAYROLL","ROBBERY,ATM LOCATION","ROBBERY,BANK","ROBBERY,BAR/RESTAURANT","ROBBERY,BEGIN AS SHOPLIFTING","ROBBERY,BICYCLE","ROBBERY,BODEGA/CONVENIENCE STORE","ROBBERY,CAR JACKING","ROBBERY,CHECK CASHING BUSINESS","ROBBERY,CLOTHING","ROBBERY,COMMERCIAL UNCLASSIFIED","ROBBERY,DELIVERY PERSON","ROBBERY,DOCTOR/DENTIST OFFICE","ROBBERY,DWELLING","ROBBERY,GAS STATION","ROBBERY,HIJACKING","ROBBERY,HOME INVASION","ROBBERY,LICENSED FOR HIRE VEHICLE","ROBBERY,LICENSED MEDALLION CAB","ROBBERY,LIQUOR STORE","ROBBERY,NECKCHAIN/JEWELRY","ROBBERY,OF TRUCK DRIVER","ROBBERY,ON BUS/ OR BUS DRIVER","ROBBERY,OPEN AREA UNCLASSIFIED","ROBBERY,PERSONAL ELECTRONIC DEVICE","ROBBERY,PHARMACY","ROBBERY,POCKETBOOK/CARRIED BAG","ROBBERY,PUBLIC PLACE INSIDE","ROBBERY,RESIDENTIAL COMMON AREA","ROBBERY,UNLICENSED FOR HIRE VEHICLE","SALE OF UNAUTHORIZED RECORDING","SALE SCHOOL GROUNDS","SALE SCHOOL GROUNDS 4","SALES OF PRESCRIPTION","SEX CRIMES","SEX TRAFFICKING","SEXUAL ABUSE","SEXUAL ABUSE 3,2","SEXUAL MISCONDUCT,DEVIATE","SEXUAL MISCONDUCT,INTERCOURSE","SMOKING TRANSPORTATION FACILIT","SODOMY 1","SODOMY 2","SODOMY 3","SODOMY,CONSENSUAL","SOLICITATION 3,2,1, CRIMINAL","SOLICITATION 4, CRIMINAL","SOLICITATION 5,CRIMINAL","STOLEN PROP-MOTOR VEHICLE 3RD,","STOLEN PROPERTY 2,1,POSSESSION","STOLEN PROPERTY 2,POSSESSION B","STOLEN PROPERTY 3,POSSESSION","STOLEN PROPERTY-MOTOR VEH 2ND,","STRANGULATION 1ST","SUPP. ACT TERR 2ND","TAMPERING 1,CRIMINAL","TAMPERING 3,2, CRIMINAL","TAMPERING WITH A WITNESS","TAX LAW","TERRORISM PROVIDE SUPPORT","THEFT OF SERVICES- CABLE TV SE","THEFT OF SERVICES, UNCLASSIFIE","THEFT,RELATED OFFENSES,UNCLASS","TORTURE/INJURE ANIMAL CRUELTY","TRAFFIC,UNCLASSIFIED INFRACTIO","TRAFFIC,UNCLASSIFIED MISDEMEAN","TRESPASS 1,CRIMINAL","TRESPASS 2, CRIMINAL","TRESPASS 3, CRIMINAL","TRESPASS 4,CRIMINAL SUB 2","UNAUTH. SALE OF TRANS. SERVICE","UNAUTHORIZED USE VEHICLE 2","UNAUTHORIZED USE VEHICLE 3","UNDER THE INFLUENCE OF DRUGS","UNLAWFUL DISCLOSURE OF AN INTIMATE IMAGE","UNLAWFUL POSS. WEAPON UPON SCH","UNLAWFUL SALE SYNTHETIC MARIJUANA","USE CHILD TO COMMIT CONT SUB OFF","USE OF A CHILD IN A SEXUAL PER","USURY,CRIMINAL","VEHICULAR ASSAULT (INTOX DRIVE","VIOLATION OF ORDER OF PROTECTI","WEAPONS DISPOSITION OF","WEAPONS POSSESSION 1 & 2","WEAPONS POSSESSION 3","WEAPONS, POSSESSION, ETC","WEAPONS,MFR,TRANSPORT,ETC.","WEAPONS,PROHIBITED USE","WEAPONS,PROHIBITED USE IMITATI","WOUNDS,REPORTING OF"];

    $( "#tags" ).autocomplete({
      source: availableTags
    });
  } );
  </script>
  </head> 

<!-- Everything inside the BODY tags are visible on page.-->
  <body>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="index.html">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="getMega.php">Reported Crimes</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Classifications and Codes
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="externalClass.php">External Classifications</a></li>
                  <li><a class="dropdown-item" href="internalClass.php">Internal Classifications</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Searching
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="complaintNumber.php">Complaint Number</a></li>
                  <li><a class="dropdown-item" href="offenseTypes.php">Offense Description</a></li>
                  <li><a class="dropdown-item" href="getLaw.php">Law Classifications</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Updating
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="insertRecord.php">Insert Report</a></li>
                  <li><a class="dropdown-item" href="updateRecord.php">Update Report</a></li>
                  <li><a class="dropdown-item" href="deleteRecord.php">Delete Report</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <h1 style="text-align: center">Search by Internal Offense Description</h1>
    <form method="post" style="text-align: center">
    <div class="ui-widget">
      <label for="tags">Offense: </label>
      <input name="offense_input" id = "tags">
      <input type="submit" name="field_submit" value="Submit">
    </div>
   </form>

  <?php
      if (isset($_POST['field_submit'])) {
        // If the query executed (result is true) and the row count returned from the query is greater than 0 then...
        if ($result && $prepared_stmt->rowCount() > 0) { ?>
              <!-- first show the header RESULT -->
              <h2 style="text-align: center">Results For: <?php echo $_POST['offense_input']; ?></h2>
              <!-- THen create a table like structure. See the project.css how table is stylized. -->
            <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">Complaint Number</th>
                    <th scope="col">Offense Date</th>
                    <th scope="col">Law Category</th>
                  </tr>
                </thead>
                <tbody>

                    <?php foreach ($result as $row) { ?>
                      <tr>
                         <!-- Print (echo) the value of mID in first column of table -->
                        <td><?php echo $row["cmplnt_num"]; ?></td>
                        <!-- Print (echo) the value of title in second column of table -->
                        <td><?php echo $row["cmplnt_fr_dt"]; ?></td>
                         <td><?php echo $row["law_cat_cd"]; ?></td>
                      <!-- End first row. Note this will repeat for each row in the $result variable-->
                      </tr>
                    <?php } ?>
                </tbody>
            </table>

        <?php } else { ?>
          <!-- IF query execution resulted in error display the following message-->
          <h3 style="text-align: center">Sorry, no results found for offense type:  <?php echo $_POST['offense_input']; ?>. </h3>
        <?php }
    } ?>


   <footer class="py-2 bg-dark" style="position:relative; bottom:0; width: 100%;">
        <div class="container px-3 px-md-3">
          <p class="m-0 text-center text-white"> CS 3265, Project Two. Created By: Chanteria Milner and Sneh Patel </p></div>
    </footer>
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>